import React, {FormEvent, useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, BarChart3, BookOpen, Brain, CheckCircle2, ChevronDown, Clock3, Copy, Flame, Menu, Moon, Play, Plus, Rocket, Sparkles, Trophy, Users, Zap} from 'lucide-react';
import {backendConfigured, supabase} from './supabase';
import './styles.css';

type View='home'|'signin'|'signup'|'dashboard';
type Community={id:string;name:string;description:string|null;category:string|null;invite_code:string};
type Activity={id:string;title:string;description:string|null;status:string;points:number;duration_seconds:number|null;created_at:string};
type QuestionDraft={question:string;options:string[];correctIndex:number;explanation:string};

const features=[
 {icon:<Zap/>,title:'Turn WhatsApp messages into participation',copy:'Post the link where your community already talks. Activa handles the activity, scores and results.'},
 {icon:<Sparkles/>,title:'Create activities in minutes',copy:'Build a quiz yourself or start with an AI-generated draft you can review and refine.'},
 {icon:<BarChart3/>,title:'See who participated',copy:'Understand engagement with clear results, completion rates and a live leaderboard.'},
 {icon:<Users/>,title:'One account, every community',copy:'Switch between every community you belong to, without juggling accounts.'}
];

function Logo({goHome}:{goHome:()=>void}){return <button className="logo logoButton" onClick={goHome}><span className="logoMark">A</span><span>Activa</span></button>}

function App(){
 const [dark,setDark]=useState(false),[menu,setMenu]=useState(false),[view,setView]=useState<View>('home'),[userEmail,setUserEmail]=useState<string|null>(null);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>{if(data.session?.user.email){setUserEmail(data.session.user.email);setView('dashboard')}});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>{setUserEmail(s?.user.email??null);if(s?.user.email)setView('dashboard')});return()=>l.subscription.unsubscribe()},[]);
 const go=(v:View)=>{setView(v);setMenu(false);window.scrollTo({top:0})};
 if(view==='signin'||view==='signup')return <AuthPage mode={view} dark={dark} onTheme={()=>setDark(!dark)} onHome={()=>go('home')} onSwitch={()=>go(view==='signin'?'signup':'signin')} onSuccess={e=>{setUserEmail(e);go('dashboard')}}/>;
 if(view==='dashboard')return <Dashboard dark={dark} email={userEmail} onTheme={()=>setDark(!dark)} onHome={()=>go('home')} onSignOut={async()=>{await supabase?.auth.signOut();setUserEmail(null);go('home')}}/>;
 return <div className={dark?'app dark':'app'}><header><div className="nav"><Logo goHome={()=>go('home')}/><nav className={menu?'open':''}><a href="#how">How it works</a><a href="#features">Features</a><a href="#community">For communities</a><button className="navLink" onClick={()=>go('signin')}>Sign in</button><button className="navCta navButton" onClick={()=>go('signup')}>Get started <ArrowRight size={16}/></button></nav><div className="navTools"><button className="iconBtn" onClick={()=>setDark(!dark)}><Moon size={19}/></button><button className="iconBtn menu" onClick={()=>setMenu(!menu)}><Menu size={21}/></button></div></div></header><main>
 <section className="hero"><div className="orb one"/><div className="orb two"/><div className="heroCopy"><div className="eyebrow"><span/><b>WHERE COMMUNITIES COME ALIVE</b></div><h1>Your community already has a place to talk.<br/><em>Now give them a place to play.</em></h1><p>Activa helps communities create quizzes, challenges and activities members can actually participate in, with scores and leaderboards built in.</p><div className="heroActions"><button className="primary actionButton" onClick={()=>go('signup')}>Create a community <ArrowRight/></button><a className="secondary" href="#demo"><Play fill="currentColor"/> Explore Activa</a></div><div className="trust"><div className="avatars"><i>AM</i><i>JO</i><i>SK</i><i>+2k</i></div><span><b>Built for real communities</b><small>Churches, clubs, cohorts & groups</small></span></div></div><Phone onPlay={()=>go('signup')}/></section>
 <section className="position" id="how"><p>KEEP THE CONVERSATION. ADD THE PARTICIPATION.</p><h2>Keep your community where they already talk.<br/><span>Use Activa for what they can't easily do there.</span></h2><div className="flow"><div><span className="wa">W</span><b>Share on WhatsApp</b><small>Drop one simple link</small></div><ArrowRight/><div><span className="act">A</span><b>Play on Activa</b><small>Quiz, challenge, complete</small></div><ArrowRight/><div><span className="win"><Trophy/></span><b>Celebrate together</b><small>Scores, streaks & ranks</small></div></div></section>
 <section className="features" id="features"><div className="sectionHead"><span>MADE FOR MOMENTUM</span><h2>Participation, made simple.</h2><p>No new group chat. No complicated setup. Just meaningful activities your members will want to join.</p></div><div className="featureGrid">{features.map((x,i)=><article key={x.title} className={'f'+i}><div>{x.icon}</div><h3>{x.title}</h3><p>{x.copy}</p><button className="learnButton" onClick={()=>go('signup')}>Get started <ArrowRight size={16}/></button></article>)}</div></section>
 <section className="cta"><div><span>READY TO BRING THE ENERGY?</span><h2>Create your first community.</h2><p>Start free. Create something your community can play today.</p></div><button className="whiteButton actionButton" onClick={()=>go('signup')}>Get started free <ArrowRight/></button></section>
 </main><footer><Logo goHome={()=>go('home')}/><p>© 2026 Activa. Where communities come alive.</p></footer></div>
}

function AuthPage({mode,dark,onTheme,onHome,onSwitch,onSuccess}:{mode:'signin'|'signup';dark:boolean;onTheme:()=>void;onHome:()=>void;onSwitch:()=>void;onSuccess:(e:string)=>void}){
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[checkEmail,setCheckEmail]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError('');if(!supabase){setError('Supabase is not connected.');return}setBusy(true);try{if(mode==='signup'){const {data,error}=await supabase.auth.signUp({email,password,options:{data:{display_name:name||email.split('@')[0]},emailRedirectTo:window.location.origin}});if(error)throw error;if(data.session)onSuccess(data.user?.email??email);else setCheckEmail(true)}else{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;onSuccess(data.user.email??email)}}catch(err){setError(err instanceof Error?err.message:'Something went wrong')}finally{setBusy(false)}}
 return <div className={dark?'app dark authApp':'app authApp'}><header><div className="nav"><Logo goHome={onHome}/><div className="authNavActions"><button className="iconBtn" onClick={onTheme}><Moon size={19}/></button><button className="navLink" onClick={onHome}>Back to home</button></div></div></header><main className="authMain"><section className="authCard">
 {checkEmail?<div className="emailSuccess"><CheckCircle2/><div className="authBadge">ONE MORE STEP</div><h1>Check your email.</h1><p>We sent a confirmation link to <b>{email}</b>. Confirm your address, then come back and sign in.</p><button className="primary actionButton" onClick={onSwitch}>Go to sign in <ArrowRight/></button></div>:<>
 <div className="authBadge">{mode==='signup'?'CREATE YOUR ACTIVA ACCOUNT':'WELCOME BACK'}</div><h1>{mode==='signup'?'Bring your community to life.':'Sign in to Activa.'}</h1><p>{mode==='signup'?'Create activities, share them on WhatsApp and see your community climb the leaderboard.':'Continue managing your communities, activities and results.'}</p>
 {!backendConfigured&&<div className="backendNotice">Backend setup required</div>}<form onSubmit={submit}>{mode==='signup'&&<label>Display name<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} required/></label>{error&&<div className="formError">{error}</div>}<button className="primary authSubmit" disabled={busy}>{busy?'Please wait...':mode==='signup'?'Create account':'Sign in'} <ArrowRight size={18}/></button></form><div className="authSwitch">{mode==='signup'?'Already have an account?':'New to Activa?'} <button onClick={onSwitch}>{mode==='signup'?'Sign in':'Create an account'}</button></div></>}
 </section><aside className="authStory"><div><span>ACTIVA</span><h2>Talk on WhatsApp.<br/>Play on Activa.</h2><p>One link turns a group conversation into a challenge, quiz or community activity.</p></div></aside></main></div>
}

function Dashboard({dark,email,onTheme,onHome,onSignOut}:{dark:boolean;email:string|null;onTheme:()=>void;onHome:()=>void;onSignOut:()=>void}){
 const [communities,setCommunities]=useState<Community[]>([]),[selected,setSelected]=useState(''),[activities,setActivities]=useState<Activity[]>([]),[loading,setLoading]=useState(true),[showCommunity,setShowCommunity]=useState(false),[showQuiz,setShowQuiz]=useState(false),[notice,setNotice]=useState('');
 const selectedCommunity=useMemo(()=>communities.find(c=>c.id===selected),[communities,selected]);
 async function load(){if(!supabase)return;setLoading(true);await supabase.rpc('ensure_my_profile');const {data,error}=await supabase.from('communities').select('id,name,description,category,invite_code').order('created_at');if(error){setNotice(error.message);setLoading(false);return}const list=(data??[]) as Community[];setCommunities(list);const cid=selected&&list.some(c=>c.id===selected)?selected:list[0]?.id??'';setSelected(cid);setLoading(false)}
 async function loadActivities(cid:string){if(!supabase||!cid){setActivities([]);return}const {data}=await supabase.from('activities').select('id,title,description,status,points,duration_seconds,created_at').eq('community_id',cid).order('created_at',{ascending:false});setActivities((data??[]) as Activity[])}
 useEffect(()=>{load()},[]);useEffect(()=>{loadActivities(selected)},[selected]);
 async function publish(a:Activity){if(!supabase)return;const next=a.status==='live'?'draft':'live';const {error}=await supabase.rpc('set_activity_status',{p_activity_id:a.id,p_status:next});if(error)setNotice(error.message);else{setNotice(next==='live'?'Activity is live and ready to share.':'Activity moved back to draft.');loadActivities(selected)}}
 function share(a:Activity){navigator.clipboard?.writeText(window.location.origin+'/?activity='+a.id);setNotice('Share link copied. Public play flow is the next piece we will connect.')}
 return <div className={dark?'app dark dashboardApp':'app dashboardApp'}><header><div className="nav"><Logo goHome={onHome}/><div className="authNavActions"><button className="iconBtn" onClick={onTheme}><Moon size={19}/></button><span className="userChip">{email}</span><button className="navLink" onClick={onSignOut}>Sign out</button></div></div></header><main className="dashShell">
  <section className="dashTop"><div><span className="authBadge">COMMUNITY COMMAND CENTRE</span><h1>Make something worth sharing.</h1><p>Create a community, build a challenge and send the link straight to the WhatsApp group.</p></div><button className="primary actionButton" onClick={()=>setShowCommunity(true)}><Plus/> New community</button></section>
  {notice&&<div className="dashNotice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
  <section className="statsRow"><div><Users/><span><b>{communities.length}</b><small>Communities</small></span></div><div><Brain/><span><b>{activities.length}</b><small>Activities</small></span></div><div><Rocket/><span><b>{activities.filter(a=>a.status==='live').length}</b><small>Live now</small></span></div><div><Trophy/><span><b>0</b><small>Participants</small></span></div></section>
  <div className="workspace">
   <aside className="communityRail"><div className="railHead"><b>Your communities</b><button onClick={()=>setShowCommunity(true)}>+</button></div>{loading?<p>Loading...</p>:communities.length===0?<div className="emptyMini"><Users/><b>No communities yet</b><span>Create your first one to unlock activities.</span></div>:communities.map(c=><button key={c.id} className={selected===c.id?'communityChoice active':'communityChoice'} onClick={()=>setSelected(c.id)}><span className="communityAvatar">{c.name.slice(0,2).toUpperCase()}</span><span><b>{c.name}</b><small>{c.category||'Community'}</small></span></button>)}</aside>
   <section className="activityArea">{selectedCommunity?<><div className="areaHead"><div><span className="authBadge">ACTIVE COMMUNITY</span><h2>{selectedCommunity.name}</h2><p>{selectedCommunity.description||'Your new Activa community is ready for its first challenge.'}</p></div><button className="secondary actionButton" onClick={()=>setShowQuiz(true)}><Plus/> Create quiz</button></div>
    {activities.length===0?<div className="emptyState"><Brain/><h3>Your activity board is empty.</h3><p>Start with a quick quiz. You can publish it, copy the share link and send it to your group.</p><button className="primary actionButton" onClick={()=>setShowQuiz(true)}>Create first quiz <ArrowRight/></button></div>:<div className="activityList">{activities.map(a=><article key={a.id}><div className="activityIcon"><Brain/></div><div className="activityCopy"><div><span className={'status '+a.status}>{a.status}</span><small>{a.points} pts • {Math.round((a.duration_seconds||300)/60)} min</small></div><h3>{a.title}</h3><p>{a.description||'Quiz activity'}</p></div><div className="activityActions"><button onClick={()=>share(a)}><Copy/> Share</button><button className="publishBtn" onClick={()=>publish(a)}>{a.status==='live'?'Unpublish':'Publish'}</button></div></article>)}</div>}</>:<div className="emptyState"><Users/><h3>Create your first community.</h3><p>Think of it as the home base for a WhatsApp group, church, club, class, cohort or team.</p><button className="primary actionButton" onClick={()=>setShowCommunity(true)}>Create community</button></div>}</section>
  </div>
 </main>{showCommunity&&<CommunityModal close={()=>setShowCommunity(false)} done={()=>{setShowCommunity(false);setNotice('Community created. Now give them something to play.');load()}}/>}{showQuiz&&selected&&<QuizModal communityId={selected} close={()=>setShowQuiz(false)} done={()=>{setShowQuiz(false);setNotice('Quiz created as a draft. Review it, then publish when ready.');loadActivities(selected)}}/>}</div>
}

function CommunityModal({close,done}:{close:()=>void;done:()=>void}){const [name,setName]=useState(''),[description,setDescription]=useState(''),[category,setCategory]=useState('Church / faith community'),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);const {error}=await supabase.rpc('create_community',{p_name:name,p_description:description,p_category:category});setBusy(false);if(error)setError(error.message);else done()}return <div className="modalShade"><form className="modalCard" onSubmit={submit}><div className="modalHead"><div><span className="authBadge">NEW COMMUNITY</span><h2>Create a home base</h2></div><button type="button" onClick={close}>×</button></div><label>Community name<input value={name} onChange={e=>setName(e.target.value)} placeholder="PSF Lagos Province 76" required/></label><label>What is this community about?<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="A place for our members to take part in weekly quizzes and challenges."/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>Church / faith community</option><option>Club</option><option>Class / cohort</option><option>Work team</option><option>Friends & social group</option><option>Other</option></select></label>{error&&<div className="formError">{error}</div>}<button className="primary authSubmit" disabled={busy}>{busy?'Creating...':'Create community'} <ArrowRight/></button></form></div>}

function QuizModal({communityId,close,done}:{communityId:string;close:()=>void;done:()=>void}){const blank=():QuestionDraft=>({question:'',options:['','','',''],correctIndex:0,explanation:''});const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[duration,setDuration]=useState(300),[questions,setQuestions]=useState<QuestionDraft[]>([blank()]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const setQ=(i:number,next:QuestionDraft)=>setQuestions(q=>q.map((x,n)=>n===i?next:x));
 async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;setError('');for(const q of questions){if(!q.question.trim()||q.options.filter(Boolean).length<2){setError('Every question needs text and at least two answer options.');return}}setBusy(true);const payload=questions.map(q=>({...q,options:q.options.filter(x=>x.trim()).map(x=>x.trim())}));const {error}=await supabase.rpc('create_quiz_activity',{p_community_id:communityId,p_title:title,p_description:description,p_duration_seconds:duration,p_questions:payload});setBusy(false);if(error)setError(error.message);else done()}
 return <div className="modalShade"><form className="modalCard quizModal" onSubmit={submit}><div className="modalHead"><div><span className="authBadge">QUIZ BUILDER</span><h2>Create a playable challenge</h2></div><button type="button" onClick={close}>×</button></div><div className="formGrid"><label>Quiz title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Bible Speed Challenge" required/></label><label>Time limit<select value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value={180}>3 minutes</option><option value={300}>5 minutes</option><option value={600}>10 minutes</option></select></label></div><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="How well do you know the book of Acts?"/></label>{questions.map((q,i)=><div className="questionBox" key={i}><div className="questionNumber">Question {i+1}</div><input value={q.question} onChange={e=>setQ(i,{...q,question:e.target.value})} placeholder="Type your question..." required/>{q.options.map((o,j)=><div className="optionRow" key={j}><input type="radio" name={'correct'+i} checked={q.correctIndex===j} onChange={()=>setQ(i,{...q,correctIndex:j})}/><input value={o} onChange={e=>{const opts=[...q.options];opts[j]=e.target.value;setQ(i,{...q,options:opts})}} placeholder={'Answer option '+(j+1)}/></div>)}</div>)}<button type="button" className="addQuestion" onClick={()=>setQuestions(q=>[...q,blank()])}><Plus/> Add another question</button>{error&&<div className="formError">{error}</div>}<button className="primary authSubmit" disabled={busy}>{busy?'Creating quiz...':'Save quiz as draft'} <ArrowRight/></button></form></div>}

function Phone({onPlay}:{onPlay:()=>void}){return <div className="phoneWrap" id="demo"><div className="floatCard fc1"><Users/><span><b>38 playing now</b><small>Your community is active</small></span></div><div className="floatCard fc2"><Flame/><span><b>7 day streak!</b><small>Keep it going</small></span></div><div className="phone"><div className="speaker"/><div className="phoneHead"><span><b>Good morning, Ada 👋</b><small>PSF — Lagos Province 76 <ChevronDown/></small></span><i>AO</i></div><div className="todayLabel"><span>TODAY'S CHALLENGE</span><i>LIVE</i></div><div className="challenge"><div className="challengeIcon"><Brain/></div><div className="pills"><b>⚡ LIVE QUIZ</b><span>38 PLAYING</span></div><h3>Bible Speed<br/>Challenge</h3><p>How well do you know the book of Acts? Ready, set, go!</p><div className="stats"><span><Brain/><b>15</b><small>QUESTIONS</small></span><span><Clock3/><b>05:00</b><small>TIME</small></span><span><Trophy/><b>100</b><small>POINTS</small></span></div><button onClick={onPlay}><Play fill="currentColor"/> PLAY NOW</button></div></div></div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
