-- Activa's security boundary and server-authoritative game engine.
create extension if not exists pgcrypto;
create type public.community_role as enum ('owner','admin','member');
create type public.activity_type as enum ('quiz','reading_challenge');
create type public.activity_status as enum ('draft','scheduled','live','paused','ended','archived');

create table public.profiles(id uuid primary key references auth.users on delete cascade, display_name text not null default 'New member', avatar_url text, is_guest boolean not null default false, created_at timestamptz default now());
create table public.communities(id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, description text, logo_url text, category text, accent_color text default '#5b45eb', invite_code text unique not null default encode(gen_random_bytes(6),'hex'), created_at timestamptz default now());
create table public.community_memberships(user_id uuid references public.profiles on delete cascade, community_id uuid references public.communities on delete cascade, role public.community_role not null default 'member', joined_at timestamptz default now(), primary key(user_id,community_id));
create table public.activities(id uuid primary key default gen_random_uuid(), community_id uuid not null references public.communities on delete cascade, creator_id uuid not null references public.profiles, type public.activity_type not null, title text not null, description text, instructions text, points int not null default 0, start_at timestamptz, end_at timestamptz, duration_seconds int check(duration_seconds is null or duration_seconds>0), status public.activity_status not null default 'draft', config jsonb not null default '{}', is_demo boolean not null default false, created_at timestamptz default now());
create table public.activity_questions(id uuid primary key default gen_random_uuid(), activity_id uuid not null references public.activities on delete cascade, community_id uuid not null references public.communities on delete cascade, question text not null, explanation text, scripture_reference text, difficulty text, points int not null default 1, position int not null);
create table public.activity_options(id uuid primary key default gen_random_uuid(), question_id uuid not null references public.activity_questions on delete cascade, activity_id uuid not null references public.activities on delete cascade, label text not null, position int not null);
-- No select policy is ever granted on this table to a member/client role.
create table public.activity_question_keys(question_id uuid primary key references public.activity_questions on delete cascade, correct_option_id uuid not null references public.activity_options, community_id uuid not null references public.communities on delete cascade);
create table public.reading_days(id uuid primary key default gen_random_uuid(), activity_id uuid not null references public.activities on delete cascade, community_id uuid not null references public.communities on delete cascade, day_number int not null check(day_number between 1 and 365), passage text not null, note text, reflection_question text, unique(activity_id,day_number));
create table public.activity_attempts(id uuid primary key default gen_random_uuid(), activity_id uuid not null references public.activities, community_id uuid not null references public.communities, user_id uuid not null references public.profiles, started_at timestamptz not null default clock_timestamp(), deadline timestamptz not null, completed_at timestamptz, status text not null default 'started', question_order uuid[] not null, option_orders jsonb not null, is_practice boolean not null default false);
create table public.activity_answers(id uuid primary key default gen_random_uuid(), attempt_id uuid not null references public.activity_attempts on delete cascade, community_id uuid not null references public.communities, question_id uuid not null references public.activity_questions, option_id uuid references public.activity_options, is_correct boolean not null, unique(attempt_id,question_id));
create table public.activity_results(id uuid primary key default gen_random_uuid(), attempt_id uuid unique not null references public.activity_attempts, activity_id uuid not null references public.activities, community_id uuid not null references public.communities, user_id uuid not null references public.profiles, score int not null, possible_score int not null, percentage numeric(5,2) not null, duration_seconds int not null, completed_at timestamptz not null default now());
create table public.reading_checkins(id uuid primary key default gen_random_uuid(), activity_id uuid not null references public.activities, reading_day_id uuid not null references public.reading_days, community_id uuid not null references public.communities, user_id uuid not null references public.profiles, completed_at timestamptz default now(), unique(reading_day_id,user_id));
create table public.points_transactions(id uuid primary key default gen_random_uuid(), community_id uuid not null references public.communities, user_id uuid not null references public.profiles, activity_id uuid references public.activities, points int not null, reason text not null, created_at timestamptz default now(), unique(user_id,activity_id,reason));
create table public.ai_generations(id uuid primary key default gen_random_uuid(), community_id uuid not null references public.communities, admin_id uuid not null references public.profiles, prompt text not null, draft jsonb not null, created_at timestamptz default now());
create table public.audit_logs(id bigint generated always as identity primary key, community_id uuid not null references public.communities, actor_id uuid not null references public.profiles, action text not null, target_id uuid, details jsonb default '{}', created_at timestamptz default now());

create index activities_community_idx on public.activities(community_id,status);
create index questions_activity_idx on public.activity_questions(activity_id,position);
create index attempts_activity_user_idx on public.activity_attempts(activity_id,user_id,completed_at);
create index results_community_completed_idx on public.activity_results(community_id,completed_at desc);
create index points_community_user_idx on public.points_transactions(community_id,user_id);
create index checkins_activity_user_idx on public.reading_checkins(activity_id,user_id);

create function public.is_member(cid uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.community_memberships where community_id=cid and user_id=auth.uid())$$;
create function public.is_admin(cid uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.community_memberships where community_id=cid and user_id=auth.uid() and role in ('owner','admin'))$$;

alter table public.profiles enable row level security; alter table public.communities enable row level security; alter table public.community_memberships enable row level security; alter table public.activities enable row level security; alter table public.activity_questions enable row level security; alter table public.activity_options enable row level security; alter table public.activity_question_keys enable row level security; alter table public.reading_days enable row level security; alter table public.activity_attempts enable row level security; alter table public.activity_answers enable row level security; alter table public.activity_results enable row level security; alter table public.reading_checkins enable row level security; alter table public.points_transactions enable row level security; alter table public.ai_generations enable row level security; alter table public.audit_logs enable row level security;
create policy "profiles visible to shared communities" on public.profiles for select using(id=auth.uid() or exists(select 1 from public.community_memberships mine join public.community_memberships theirs using(community_id) where mine.user_id=auth.uid() and theirs.user_id=profiles.id));
create policy "own profile" on public.profiles for update using(id=auth.uid());
create policy "member communities" on public.communities for select using(public.is_member(id));
create policy "member memberships" on public.community_memberships for select using(public.is_member(community_id));
create policy "member activities" on public.activities for select using(public.is_member(community_id) and (status<>'draft' or public.is_admin(community_id)));
create policy "admin activities" on public.activities for all using(public.is_admin(community_id)) with check(public.is_admin(community_id));
create policy "member questions" on public.activity_questions for select using(public.is_member(community_id));
create policy "admin questions" on public.activity_questions for all using(public.is_admin(community_id)) with check(public.is_admin(community_id));
create policy "member options" on public.activity_options for select using(exists(select 1 from public.activities a where a.id=activity_id and public.is_member(a.community_id)));
create policy "admin options" on public.activity_options for all using(exists(select 1 from public.activities a where a.id=activity_id and public.is_admin(a.community_id)));
create policy "admin keys write only" on public.activity_question_keys for insert with check(public.is_admin(community_id));
create policy "admin keys update" on public.activity_question_keys for update using(public.is_admin(community_id));
create policy "member reading days" on public.reading_days for select using(public.is_member(community_id));
create policy "own or admin attempts" on public.activity_attempts for select using(user_id=auth.uid() or public.is_admin(community_id));
create policy "own or admin answers" on public.activity_answers for select using(exists(select 1 from public.activity_attempts a where a.id=attempt_id and (a.user_id=auth.uid() or public.is_admin(a.community_id))));
create policy "own or admin results" on public.activity_results for select using(user_id=auth.uid() or public.is_admin(community_id));
create policy "own checkins read" on public.reading_checkins for select using(user_id=auth.uid() or public.is_admin(community_id));
create policy "own points read" on public.points_transactions for select using(user_id=auth.uid() or public.is_admin(community_id));
create policy "admin generations" on public.ai_generations for select using(admin_id=auth.uid() and public.is_admin(community_id));
create policy "admin audits" on public.audit_logs for select using(public.is_admin(community_id));

create view public.community_leaderboard with (security_invoker=true) as select p.community_id,p.user_id,pr.display_name,pr.avatar_url,sum(p.points)::bigint points,rank() over(partition by p.community_id order by sum(p.points) desc) rank from public.points_transactions p join public.profiles pr on pr.id=p.user_id group by p.community_id,p.user_id,pr.display_name,pr.avatar_url;

-- Correct keys remain inside SECURITY DEFINER RPCs and never enter start_attempt's response.
create function public.start_attempt(p_activity_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare a public.activities; aid uuid:=gen_random_uuid(); qids uuid[]; opts jsonb; prior int; begin select * into a from public.activities where id=p_activity_id and status='live' and (end_at is null or end_at>clock_timestamp()); if not found then raise exception 'Activity is not live'; end if; if auth.uid() is null then raise exception 'Authentication required'; end if; if not public.is_member(a.community_id) and not exists(select 1 from public.profiles where id=auth.uid() and is_guest) then raise exception 'Membership required'; end if; select count(*) into prior from public.activity_attempts where activity_id=a.id and user_id=auth.uid() and is_practice=false; if coalesce((a.config->>'attempts_allowed')::int,1)>0 and prior>=coalesce((a.config->>'attempts_allowed')::int,1) then raise exception 'No attempts remaining'; end if; select array_agg(id order by case when coalesce((a.config->>'randomise_questions')::boolean,false) then random() else position end) into qids from public.activity_questions where activity_id=a.id; select jsonb_object_agg(question_id,items) into opts from (select o.question_id,jsonb_agg(jsonb_build_object('id',o.id,'label',o.label) order by case when coalesce((a.config->>'randomise_answers')::boolean,false) then random() else o.position end) items from public.activity_options o where o.activity_id=a.id group by o.question_id)s; insert into public.activity_attempts(id,activity_id,community_id,user_id,deadline,question_order,option_orders,is_practice) values(aid,a.id,a.community_id,auth.uid(),clock_timestamp()+make_interval(secs=>a.duration_seconds+5),qids,opts,coalesce((a.config->>'practice')::boolean,false)); return jsonb_build_object('attempt_id',aid,'deadline',(select deadline from public.activity_attempts where id=aid),'questions',(select jsonb_agg(jsonb_build_object('id',q.id,'question',q.question,'scripture_reference',q.scripture_reference,'options',opts->q.id::text) order by array_position(qids,q.id)) from public.activity_questions q where q.id=any(qids))); end$$;

create function public.submit_attempt(p_attempt_id uuid,p_answers jsonb) returns jsonb language plpgsql security definer set search_path='' as $$declare at public.activity_attempts; a public.activities; sc int; poss int; pct numeric; rnk bigint; begin select * into at from public.activity_attempts where id=p_attempt_id and user_id=auth.uid() for update; if not found then raise exception 'Attempt not found'; end if; if at.completed_at is not null then raise exception 'Attempt already submitted'; end if; if clock_timestamp()>at.deadline then raise exception 'Submission window closed'; end if; select * into a from public.activities where id=at.activity_id; insert into public.activity_answers(attempt_id,community_id,question_id,option_id,is_correct) select at.id,at.community_id,x.question_id,x.option_id,(k.correct_option_id=x.option_id) from jsonb_to_recordset(p_answers) x(question_id uuid,option_id uuid) join public.activity_question_keys k using(question_id) on conflict(attempt_id,question_id) do nothing; select coalesce(sum(q.points) filter(where aa.is_correct),0),coalesce(sum(q.points),0) into sc,poss from public.activity_questions q left join public.activity_answers aa on aa.question_id=q.id and aa.attempt_id=at.id where q.activity_id=at.activity_id; pct:=case when poss=0 then 0 else round(sc*100.0/poss,2) end; update public.activity_attempts set completed_at=clock_timestamp(),status='completed' where id=at.id; insert into public.activity_results(attempt_id,activity_id,community_id,user_id,score,possible_score,percentage,duration_seconds) values(at.id,at.activity_id,at.community_id,at.user_id,sc,poss,pct,extract(epoch from(clock_timestamp()-at.started_at))); if not at.is_practice then insert into public.points_transactions(community_id,user_id,activity_id,points,reason) values(at.community_id,at.user_id,at.activity_id,sc,'quiz_completion') on conflict do nothing; end if; select rank into rnk from (select user_id,rank() over(order by score desc,duration_seconds asc,completed_at asc) rank from public.activity_results where activity_id=at.activity_id)t where user_id=at.user_id; return jsonb_build_object('score',sc,'possible_score',poss,'percentage',pct,'rank',rnk,'correct_answers',case when coalesce((a.config->>'show_answers')::boolean,false) then (select jsonb_agg(jsonb_build_object('question_id',k.question_id,'option_id',k.correct_option_id,'explanation',q.explanation)) from public.activity_question_keys k join public.activity_questions q on q.id=k.question_id where q.activity_id=a.id) else null end); end$$;
revoke all on function public.start_attempt(uuid) from public; revoke all on function public.submit_attempt(uuid,jsonb) from public; grant execute on function public.start_attempt(uuid),public.submit_attempt(uuid,jsonb) to authenticated;
